from __future__ import annotations

import html as _html
from datetime import UTC, datetime

import markdown as _md
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.finding import Finding, Severity
from app.models.report import Report, ReportType, RiskRating

_RISK_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#d97706",
    "low": "#65a30d",
    "informational": "#6b7280",
}

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{ --risk: {risk_color}; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 900px; margin: 2rem auto; padding: 0 1.5rem;
         color: #111827; line-height: 1.6; }}
  h1 {{ font-size: 1.875rem; border-bottom: 3px solid var(--risk); padding-bottom: .5rem; }}
  h2 {{ font-size: 1.25rem; margin-top: 2rem; color: #1f2937; }}
  h3 {{ font-size: 1rem; color: #374151; margin-top: 1.5rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th {{ background: #f3f4f6; text-align: left; padding: .5rem .75rem; }}
  td {{ padding: .5rem .75rem; border-top: 1px solid #e5e7eb; }}
  code {{ background: #f3f4f6; padding: .1em .3em; border-radius: 3px; font-size: .9em; }}
  .risk-badge {{ display: inline-block; padding: .25rem .75rem; border-radius: 9999px;
                 background: var(--risk); color: #fff; font-weight: 600;
                 font-size: .85rem; text-transform: uppercase; }}
  .meta {{ color: #6b7280; font-size: .9rem; margin-bottom: 1.5rem; }}
  hr {{ border: none; border-top: 1px solid #e5e7eb; margin: 2rem 0; }}
  .footer {{ color: #9ca3af; font-size: .8rem; text-align: center; margin-top: 3rem; }}
  ul {{ padding-left: 1.5rem; }}
  li {{ margin: .25rem 0; }}
  strong {{ color: #111827; }}
</style>
</head>
<body>
{body}
<p class="footer">Generated by DVAP &mdash; Damn Vulnerable AI Platform</p>
</body>
</html>
"""

OWASP_LLM_TOP10 = [
    {"id": "LLM01", "name": "Prompt Injection", "categories": ["prompt_injection", "tool_injection"]},
    {"id": "LLM02", "name": "Insecure Output Handling", "categories": ["data_exfiltration", "browser_agent"]},
    {"id": "LLM03", "name": "Training Data Poisoning", "categories": ["rag_poisoning", "supply_chain"]},
    {"id": "LLM04", "name": "Model Denial of Service", "categories": []},
    {"id": "LLM05", "name": "Supply-Chain Vulnerabilities", "categories": ["supply_chain"]},
    {"id": "LLM06", "name": "Sensitive Information Disclosure", "categories": ["data_exfiltration", "healthcare", "banking"]},
    {"id": "LLM07", "name": "Insecure Plugin Design", "categories": ["mcp_security", "tool_injection"]},
    {"id": "LLM08", "name": "Excessive Agency", "categories": ["autonomous_agent", "multi_agent", "browser_agent"]},
    {"id": "LLM09", "name": "Overreliance", "categories": []},
    {"id": "LLM10", "name": "Model Theft", "categories": ["supply_chain"]},
]

MITRE_ATLAS_TECHNIQUES = [
    {"id": "AML.T0051", "name": "LLM Prompt Injection", "categories": ["prompt_injection"]},
    {"id": "AML.T0054", "name": "LLM Jailbreak", "categories": ["prompt_injection", "memory_poisoning"]},
    {"id": "AML.T0048", "name": "Backdoor ML Model", "categories": ["supply_chain"]},
    {"id": "AML.T0020", "name": "Poison Training Data", "categories": ["rag_poisoning"]},
    {"id": "AML.T0043", "name": "Craft Adversarial Data", "categories": ["rag_poisoning", "prompt_injection"]},
    {"id": "AML.T0058", "name": "LLM Data Leakage", "categories": ["data_exfiltration"]},
    {"id": "AML.T0068", "name": "LLM Plugin Compromise", "categories": ["mcp_security", "tool_injection"]},
    {"id": "AML.T0053", "name": "Indirect Prompt Injection", "categories": ["prompt_injection", "rag_poisoning"]},
    {"id": "AML.T0063", "name": "Discover ML Artifacts", "categories": ["supply_chain"]},
    {"id": "AML.T0025", "name": "Exfiltrate ML Artifacts", "categories": ["data_exfiltration", "supply_chain"]},
]


def _severity_priority(severity: str) -> int:
    return {"critical": 5, "high": 4, "medium": 3, "low": 2, "informational": 1}.get(severity, 0)


def _overall_risk(findings: list[Finding]) -> str:
    if not findings:
        return RiskRating.INFORMATIONAL
    max_sev = max(findings, key=lambda f: _severity_priority(f.severity))
    sev_map = {
        "critical": RiskRating.CRITICAL,
        "high": RiskRating.HIGH,
        "medium": RiskRating.MEDIUM,
        "low": RiskRating.LOW,
    }
    return sev_map.get(max_sev.severity, RiskRating.INFORMATIONAL)


def _build_owasp_mapping(findings: list[Finding], lab_category: str | None = None) -> list[dict]:
    relevant = []
    for item in OWASP_LLM_TOP10:
        matched_findings = [
            f for f in findings
            if item["id"] in f.owasp_categories
        ]
        if lab_category and lab_category in item["categories"]:
            relevant.append({**item, "finding_count": len(matched_findings), "matched": True})
        elif matched_findings:
            relevant.append({**item, "finding_count": len(matched_findings), "matched": True})
    return relevant


def _build_mitre_mapping(findings: list[Finding], lab_category: str | None = None) -> list[dict]:
    relevant = []
    for item in MITRE_ATLAS_TECHNIQUES:
        matched = [f for f in findings if item["id"] in f.mitre_atlas]
        if lab_category and lab_category in item["categories"]:
            relevant.append({**item, "finding_count": len(matched), "matched": True})
        elif matched:
            relevant.append({**item, "finding_count": len(matched), "matched": True})
    return relevant


def _generate_executive_md(
    name: str,
    findings: list[Finding],
    owasp: list[dict],
    mitre: list[dict],
    lab_slug: str | None,
    risk_rating: str,
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    critical = sum(1 for f in findings if f.severity == "critical")
    high = sum(1 for f in findings if f.severity == "high")
    medium = sum(1 for f in findings if f.severity == "medium")
    low = sum(1 for f in findings if f.severity == "low")

    lines = [
        f"# {name}",
        f"\n**Generated:** {now}  ",
        f"**Report Type:** Executive Summary  ",
        f"**Overall Risk Rating:** {risk_rating.upper()}  ",
        *([ f"**Lab Environment:** {lab_slug}" ] if lab_slug else []),
        "\n---\n",
        "## Executive Summary\n",
        f"This report summarizes the security assessment findings from DVAP (Damn Vulnerable AI Platform). "
        f"A total of **{len(findings)} findings** were identified across the evaluated AI systems and components.",
        "",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| Critical | {critical} |",
        f"| High | {high} |",
        f"| Medium | {medium} |",
        f"| Low | {low} |",
        "",
        "## Key Risk Areas\n",
    ]

    if owasp:
        lines.append("**OWASP LLM Top 10 Coverage:**")
        for item in owasp[:5]:
            lines.append(f"- **{item['id']}** — {item['name']} ({item['finding_count']} findings)")
        lines.append("")

    if mitre:
        lines.append("**MITRE ATLAS Techniques Observed:**")
        for item in mitre[:5]:
            lines.append(f"- **{item['id']}** — {item['name']}")
        lines.append("")

    lines += [
        "## Recommendations\n",
        "1. Prioritize remediation of Critical and High severity findings immediately",
        "2. Implement prompt injection defenses at all LLM input boundaries",
        "3. Enforce least-privilege for all AI agent tool access",
        "4. Establish continuous monitoring using the AI-SOC module",
        "5. Run automated benchmarks monthly to track security posture regression",
        "",
        "---",
        "*Generated by DVAP — Damn Vulnerable AI Platform*",
    ]

    return "\n".join(lines)


def _generate_technical_md(
    name: str,
    findings: list[Finding],
    owasp: list[dict],
    mitre: list[dict],
    lab_slug: str | None,
    risk_rating: str,
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# {name}",
        f"\n**Generated:** {now}  ",
        f"**Report Type:** Technical  ",
        f"**Overall Risk Rating:** {risk_rating.upper()}  ",
        *([ f"**Lab:** {lab_slug}" ] if lab_slug else []),
        "\n---\n",
        "## Findings Detail\n",
    ]

    if not findings:
        lines.append("*No findings recorded.*\n")
    else:
        for i, f in enumerate(sorted(findings, key=lambda x: _severity_priority(x.severity), reverse=True), 1):
            lines += [
                f"### {i}. {f.title}",
                f"**Severity:** {f.severity.upper()}  ",
                f"**Status:** {f.status}  ",
                *([ f"**Attack Vector:** {f.attack_vector}" ] if f.attack_vector else []),
                "",
                f.description,
                "",
            ]
            if f.owasp_categories:
                lines.append(f"**OWASP:** {', '.join(f.owasp_categories)}  ")
            if f.mitre_atlas:
                lines.append(f"**MITRE ATLAS:** {', '.join(f.mitre_atlas)}  ")
            if f.cwe:
                lines.append(f"**CWE:** {', '.join(f.cwe)}  ")
            if f.remediation:
                lines += ["", "**Remediation:**", f.remediation]
            lines.append("")

    lines += [
        "## OWASP LLM Top 10 Mapping\n",
        "| ID | Name | Findings |",
        "|----|------|----------|",
        *[f"| {i['id']} | {i['name']} | {i['finding_count']} |" for i in owasp],
        "" if owasp else "| — | No mappings identified | 0 |",
        "",
        "## MITRE ATLAS Mapping\n",
        "| Technique ID | Name | Findings |",
        "|--------------|------|----------|",
        *[f"| {i['id']} | {i['name']} | {i['finding_count']} |" for i in mitre],
        "" if mitre else "| — | No techniques mapped | 0 |",
        "",
        "---",
        "*Generated by DVAP — Damn Vulnerable AI Platform*",
    ]

    return "\n".join(lines)


def _generate_html(name: str, content_md: str, risk_rating: str) -> str:
    body = _md.markdown(
        content_md,
        extensions=["tables", "fenced_code"],
    )
    safe_title = _html.escape(name)
    color = _RISK_COLORS.get(risk_rating, _RISK_COLORS["informational"])
    return _HTML_TEMPLATE.format(title=safe_title, risk_color=color, body=body)


async def generate_report(
    db: AsyncSession,
    name: str,
    report_type: str,
    lab_slug: str | None = None,
    lab_category: str | None = None,
) -> Report:
    stmt = select(Finding)
    if lab_slug:
        from app.services.lab_service import get_lab_by_slug
        lab = await get_lab_by_slug(db, lab_slug)
        if lab:
            stmt = stmt.where(Finding.lab_id == lab.id)
            lab_category = lab.category

    result = await db.execute(stmt)
    findings = list(result.scalars().all())

    owasp = _build_owasp_mapping(findings, lab_category)
    mitre = _build_mitre_mapping(findings, lab_category)
    risk = _overall_risk(findings)

    if report_type == ReportType.EXECUTIVE:
        content = _generate_executive_md(name, findings, owasp, mitre, lab_slug, risk)
    else:
        content = _generate_technical_md(name, findings, owasp, mitre, lab_slug, risk)

    report = Report(
        name=name,
        report_type=report_type,
        lab_slug=lab_slug,
        risk_rating=risk,
        content_md=content,
        content_html=_generate_html(name, content, risk),
        content_json={
            "findings_count": len(findings),
            "owasp_mapping": owasp,
            "mitre_mapping": mitre,
        },
        owasp_mapping=owasp,
        mitre_mapping=mitre,
        findings_count=len(findings),
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)
    return report
